---
  
apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: default
spec:
  selector:
    app: sample
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer