---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  namespace: default
  labels:
    app: sample
spec:
  selector:
    matchLabels:
      app: sample
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      name: sample
      labels:
        app: sample
    spec:
      containers:
        - name: sample
          image: 594483618195.dkr.ecr.us-east-1.amazonaws.com/samplemsforeks:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 1024M
            requests:
              cpu: 150m
              memory: 256M
      restartPolicy: Always