kind: Service
apiVersion: v1
metadata:
  name: server-demo
  labels:
    app: server-demo
    env: dev
spec:
  type: LoadBalancer
  selector:
    app: server-demo
  ports:
    - port: 80
      targetPort: 8080