server:
  port: 8080
  shutdown: graceful
spring:
  main:
    lazy-initialization: true
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: "SampleJavaSpringService"
app:
  name: SampleJavaSpringService
  version: "1"
  kubernetes:
    URLRedirect: "/api/sampleJavaSpringService"