server:
  port: 8080
  shutdown: graceful
spring:
  main:
    lazy-initialization: true
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: "SampleJavaSpringService"
app:
  name: SampleJavaSpringService
  version: "1"
  kubernetes:
    URLRedirect: "/api/sampleJavaSpringService"
  aws_access_key: ${AWS_ACCESS_KEY_FROM_K8S}
  aws_secret_key: ${AWS_SECRET_KEY_FROM_K8S}